'use strict';
// Offline design prototype. No API requests, downloads or real credentials.
const $=s=>document.querySelector(s);
const models=[
 {id:'qwen27',name:'Qwen3.8-27B',repo:'Vontra/Qwen3.8-27B-MLX-4bit',size:'16.2 GB',family:'Qwen',quant:'MLX affine 4-bit',draft:'可选 DFlash2 / context copies',loaded:true,requests:864},
 {id:'nemotron',name:'Nemotron 3.5 Lightning',repo:'Vontra/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-MLX-4bit',size:'18.5 GB',family:'Nemotron',quant:'4-bit / group-64',draft:'包含 MTP head',loaded:false,requests:242},
 {id:'flash',name:'Qwen3.8 Flash Next',repo:'Vontra/Qwen3.8-Flash-Next-MLX-4bit-MTP',size:'47.6 GB',family:'Qwen',quant:'4-bit / group-32',draft:'包含 MTP head',loaded:false,requests:128},
 {id:'glm',name:'GLM-5.3-Flash',repo:'Vontra/GLM-5.3-Flash-MLX-4bit-MTP',size:'约 180 GB',family:'GLM',quant:'4-bit / group-64',draft:'MTP · 256 GB Mac',loaded:false,requests:0},
 {id:'gemma',name:'Gemma 4 26B-A4B',repo:'mlx-community/gemma-4-26b-a4b-it-4bit',size:'16.0 GB',family:'Gemma',quant:'4-bit / group-32 或 64',draft:'context copies / 可选 DFlash',loaded:false,requests:0}
];
const menus=[['运行',[['overview','◫','运行总览'],['stats','▥','统计与用量'],['cache','▤','缓存管理']]],['模型',[['models','▦','模型库'],['downloads','↓','模型下载器','1'],['model-config','⚒','模型配置'],['model-tools','◇','量化与上传']]],['服务',[['engine-config','⚙','推理框架配置'],['server','▣','服务器与目录'],['api','⌘','API 与集成'],['auth','♧','认证与密钥'],['updates','↻','版本与更新']]],['工具',[['logs','≋','运行日志'],['bench','◷','基准测试'],['chat','□','内置聊天'],['capabilities','⊞','功能适配表']]]];
let state={page:'overview',running:true,model:'qwen27',configModel:'qwen27',forms:{},scope:'累计总计',statsModel:'all',downloadsTab:'catalog',modelTab:'installed',modelConfigTab:'sampling',cacheTab:'engine',apiTab:'endpoints',toolsTab:'quantize',benchTab:'throughput',capTab:'all',logLevel:'all',logQuery:'',pending:false,toolJobs:[],accuracyQueue:[],updateStage:0,updateFail:false,benchmarkDone:false,chatBusy:false,chatHistory:[],favorites:new Set(['qwen27']),jobs:[{id:'job1',model:'Qwen3.8 Flash Next',source:'HF 国内镜像',progress:62,paused:false,canceled:false}],keys:[{name:'本机开发工具',masked:'tf_demo_••••_72af',permission:'推理 API',status:'启用',usage:'128 次'}],engineVersion:'0.3.6.2',lastVersion:'0.3.6.1'};
let toastTimer,modalCallback=null,chatTimer=null;
const escapeHtml=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tag=(t,c='')=>`<span class="tf-tag ${c}">${t}</span>`;
const button=(text,action,value='',cls='')=>`<button class="${cls}" data-action="${action}" data-value="${escapeHtml(value)}">${text}</button>`;
const note=(t,w=false)=>`<div class="tf-note${w?' warn':''}">${t}</div>`;
const kv=(a,b)=>`<div class="tf-kv"><span>${a}</span><span>${b}</span></div>`;
const card=(title,content,action='')=>`<div class="tf-card"><div class="tf-row"><h2>${title}</h2>${action}</div>${content}</div>`;
const metric=(a,b,u='',n='示例数据')=>`<div class="tf-metric"><div class="tf-metric-label">${a}</div><div class="tf-value">${b} <small>${u}</small></div><div class="tf-metric-note">${n}</div></div>`;
const table=(cols,rows)=>`<div class="tf-table-wrap"><table class="tf-table"><thead><tr>${cols.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
const heading=(title,desc,actions='',eyebrow='LOCAL INFERENCE WORKSPACE')=>`<div class="tf-heading"><div><div class="tf-eyebrow">${eyebrow}</div><h1>${title}</h1><div class="tf-sub">${desc}</div></div><div class="tf-actions">${actions}</div></div>`;
const tabs=(items,key)=>`<div class="tf-tabs">${items.map(([val,text])=>`<button class="tf-tab ${state[key]===val?'active':''}" data-action="tab" data-value="${key}:${val}">${text}</button>`).join('')}</div>`;
const field=(label,value,hint='',type='text',id='')=>{id=id||'field-'+label.replace(/[^\p{L}\p{N}]+/gu,'-');return `<div class="tf-field"><label${id?` for="${id}"`:''}>${label}</label><input ${id?`id="${id}"`:''} type="${type}" value="${escapeHtml(value)}">${hint?`<div class="tf-sub">${hint}</div>`:''}</div>`;};
const select=(label,items,id='',value='')=>{id=id||'field-'+label.replace(/[^\p{L}\p{N}]+/gu,'-');return `<div class="tf-field"><label${id?` for="${id}"`:''}>${label}</label><select ${id?`id="${id}"`:''}>${items.map(x=>`<option ${x===value?'selected':''}>${x}</option>`).join('')}</select></div>`;};
const check=(text,on=true)=>`<label class="tf-check"><input type="checkbox" ${on?'checked':''}> ${text}</label>`;
const form=(items)=>`<div class="tf-form-grid">${items.join('')}</div>`;
const current=()=>models.find(m=>m.id===state.model);
const configCurrent=()=>models.find(m=>m.id===state.configModel);
const chart=(purple=false)=>`<div class="tf-chart"><svg viewBox="0 0 700 130" preserveAspectRatio="none"><defs><linearGradient id="tf-grad${purple?'2':''}" x1="0" y1="0" x2="0" y2="1"><stop stop-color="${purple?'#aa84eb':'#7997f2'}" stop-opacity=".22"/><stop offset="1" stop-color="#fff" stop-opacity="0"/></linearGradient></defs><path d="M0 95 L30 100 L58 77 L88 84 L118 56 L147 69 L177 43 L208 57 L237 45 L267 59 L296 32 L327 48 L356 32 L386 45 L417 23 L448 33 L478 20 L509 34 L540 20 L570 31 L601 17 L630 26 L662 18 L700 21 L700 130 L0 130Z" fill="url(#tf-grad${purple?'2':''})"/><path d="M0 95 L30 100 L58 77 L88 84 L118 56 L147 69 L177 43 L208 57 L237 45 L267 59 L296 32 L327 48 L356 32 L386 45 L417 23 L448 33 L478 20 L509 34 L540 20 L570 31 L601 17 L630 26 L662 18 L700 21" fill="none" stroke="${purple?'#9c7be0':'#6b8bec'}" stroke-width="2.5"/></svg></div><div class="tf-chart-legend"><span>5 分钟前</span><span>最近完成请求 · 示例</span><span>现在</span></div>`;
function toast(t){$('#toast').textContent=t;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,3300)}
function dialog(title,body,label,fn){modalCallback=fn;$('#modal-title').textContent=title;$('#modal-body').innerHTML=body;$('#modal-actions').innerHTML=button('取消','dismiss')+button(label,'confirm','','primary');$('#modal').hidden=false}
function dismiss(){$('#modal').hidden=true;modalCallback=null}
function go(page){state.page=page;render();window.scrollTo({top:0});if(location.hash!==`#${page}`)history.replaceState(null,'',`#${page}`)}
function formKey(){return [state.page,state.page==='model-config'?state.configModel:'',state.page==='model-config'?state.modelConfigTab:'',state.page==='cache'?state.cacheTab:'',state.page==='api'?state.apiTab:''].join(':')}
function saveForm(){const data={};document.querySelectorAll('#page .tf-field input[id],#page .tf-field select[id],#page .tf-field textarea[id]').forEach(el=>data[el.id]=el.value);state.forms[formKey()]=data}
function restoreForm(){const data=state.forms[formKey()]||{};document.querySelectorAll('#page .tf-field input[id],#page .tf-field select[id],#page .tf-field textarea[id]').forEach(el=>{if(Object.hasOwn(data,el.id))el.value=data[el.id]})}
function render(){
 $('#navigation').innerHTML=menus.map(([group,items])=>`<div class="tf-nav-group">${group}</div>${items.map(([id,icon,label,badge])=>`<button class="tf-nav ${state.page===id?'active':''}" data-action="goto" data-value="${id}"><span class="tf-nav-icon">${icon}</span>${label}${badge?`<small>${state.jobs.filter(j=>!j.canceled).length}</small>`:''}</button>`).join('')}`).join('');
 const names=menus.flatMap(x=>x[1]);$('#breadcrumbs').textContent=`工作台 / ${names.find(x=>x[0]===state.page)?.[2]||'运行总览'}`;
 $('#page').innerHTML=pages[state.page]();restoreForm();$('#task-count').textContent=state.jobs.filter(j=>!j.canceled).length;$('#footer-state').textContent=`管理界面在线 · ${state.running?'推理服务运行中':'推理服务已停止'}（演示）`;
}
const pages={};
pages.overview=()=>heading('运行总览','从服务状态到每次生成，查看本机推理工作台的全貌。',button('调整布局','layout')+button('打开聊天','goto','chat','primary'))+
 card(`<i class="tf-led" style="background:${state.running?'#16886e':'#a3adbd'}"></i>${state.running?'服务运行中':'服务已停止'}`,`<div class="tf-actions" style="margin-top:12px">${tag(current().name,'blue')}${tag('MLX / Metal')}${tag('引擎 '+state.engineVersion)}${tag(state.running?'Health: ready':'Health: offline',state.running?'green':'amber')}</div><div class="tf-grid three" style="margin-top:14px"><div>${kv('API 网关','127.0.0.1:8080/v1')}${kv('启动时间',state.running?'09:12:34 · 示例':'—')}</div><div>${kv('引擎进程',state.running?'PID 48271 · 示例':'—')}${kv('心跳采集','10:28:42 · 示例')}</div><div>${kv('管理服务','127.0.0.1:8081')}${kv('配置状态',state.pending?tag('待重启生效','amber'):tag('已同步 · 示例','green'))}</div></div>`, `<div class="tf-actions">${button('重启','service','restart')}${button(state.running?'停止服务':'启动服务','service',state.running?'stop':'start',state.running?'danger':'primary')}</div>`)+
 `<div class="tf-metrics">${metric('累计请求','1,234','次','总计 · 失败 12 · 取消 8')}${metric('最近生成速度',state.running?'72.4':'—','tok/s','decode · 最近完成请求')}${metric('最近首字延迟',state.running?'0.86':'—','秒','TTFT · 最近完成请求')}${metric('引擎活动内存',state.running?'24.8':'—','GB','MLX active · 非进程 RSS')}</div>`+
 `<div class="tf-grid split">${card('活动模型',`<div class="tf-model-title">${current().name}</div><div class="tf-model-repo">${current().repo}</div><div class="tf-chips">${tag(current().quant)}${tag(current().draft)}</div><div class="tf-divider"></div>${table(['状态','处理中 / 排队','当前阶段','生成 tokens'],[[tag(state.running?'生成中':'未加载',state.running?'green':''),state.running?'1 / 0':'0 / 0',state.running?'Decode · 5.4 s':'—',state.running?'326':'—']])}<div style="margin-top:16px">${chart()}</div>`,button('模型配置 →','goto','model-config','compact'))}${card('系统与缓存',`${kv('主机','Mac Studio · 示例硬件')}${kv('内存总量','256 GB')}${kv('系统已用','58.2 GB')}<div class="tf-bar"><i style="width:23%"></i></div>${kv('内存压力',tag('正常','green'))}${kv('MLX active / cache / peak','24.8 / 3.2 / 31.1 GB')}${kv('前缀缓存命中率','64.8% · 示例')}${kv('Draft 接受率','78.6% · 示例')}${kv('模型目录占用','98.3 GB · 示例')}`,button('查看缓存 →','goto','cache','compact'))}</div>`+
 `<div class="tf-grid two" style="margin-top:18px">${card('API 与客户端',`${kv('OpenAI Base URL','http://127.0.0.1:8080/v1')}${kv('认证状态',tag('需要 API Key · 演示','green'))}<div class="tf-chips">${tag('Chat Completions')}${tag('SSE')}${tag('Tool calling')}</div>${button('端点与接入示例','goto','api','compact')}`)}${card('版本与运行环境',`${kv('TensorFold 引擎',state.engineVersion+' · 示例安装')}${kv('管理 App','0.2.0 · 原型')}${kv('MLX / Python','0.32.2 / 3.11 · 示例')}${kv('版本检测',state.updateStage?'已检查（模拟）':'未检查')}<div class="tf-actions">${button('GitHub 一键检查','update-check')}${button('运行日志','goto','logs')}</div>`)}</div>`+
 card('最近请求',table(['时间','模型','状态','输入 / 输出','TTFT','Decode','总耗时'],[['10:28:08',current().name,tag(state.running?'处理中':'已完成',state.running?'blue':'green'),'2,048 / 326','0.86 s','72.4 tok/s','5.4 s'],['10:27:42','Qwen3.8-27B',tag('完成','green'),'1,286 / 512','0.64 s','71.6 tok/s','8.2 s'],['10:26:21','Nemotron',tag('客户端取消','amber'),'4,096 / 128','1.22 s','51.8 tok/s','3.7 s']]),button('统计与详情 →','goto','stats','compact'));
pages.stats=()=>{
 const m=state.statsModel==='all'?null:models.find(m=>m.id===state.statsModel);const count=m?m.requests:1234;const session=state.scope==='本次运行';
 return heading('统计与用量','累计、本次运行与各模型统计分开查看；只统计经过管理网关的请求。',button('导出统计 CSV','export-stats')+button('重置此范围统计','clear-stats','','danger'))+
 `<div class="tf-toolbar"><div class="tf-tabs">${['本次运行','累计总计'].map(x=>button(x,'scope',x,`tf-tab ${state.scope===x?'active':''}`)).join('')}</div><div class="tf-inline-filters"><select id="stats-model" aria-label="统计模型"><option value="all">全部模型</option>${models.map(m=>`<option value="${m.id}" ${state.statsModel===m.id?'selected':''}>${m.name}</option>`).join('')}</select><select id="stats-range" aria-label="统计时间范围"><option>今天</option><option>昨天</option><option>过去 7 天</option><option>过去 30 天</option><option>过去 90 天</option><option>本月</option><option>全部时间</option></select></div></div>`+
 `<div class="tf-metrics">${metric('请求总数',session?Math.round(count*.16):count,'次',state.scope+' · 示例')}${metric('输入 tokens',m?'1.08 M':'2.86 M','','含命中缓存 tokens')}${metric('输出 tokens',m?'426 K':'624 K','','不含输入 tokens')}${metric('成功率',count?'98.4':'—','%', '取消请求单独统计')}</div>`+
 `<div class="tf-grid two">${card('用量趋势',`${chart()}${note('时间范围与模型筛选在原型中可切换；图表为布局示例，真实统计需管理层采集。')}`)}${card('响应质量与延迟',`${kv('平均 TTFT',count?'0.92 秒':'—')}${kv('P95 TTFT',count?'2.18 秒':'—')}${kv('平均 decode',count?'68.2 tok/s':'—')}${kv('平均总耗时',count?'8.7 秒':'—')}${kv('失败 / 取消',count?'12 / 8':'0 / 0')}${kv('缓存 tokens',count?'1.85 M · 64.8%':'—')}${kv('峰值并发',count?'3':'—')}`)}</div>`+
 card('各模型累计明细',table(['模型','请求','输入 tokens','输出 tokens','缓存命中','平均 TTFT','Decode','失败'],models.filter(x=>!m||x.id===m.id).map((x,i)=>[x.name,x.requests,x.requests?['1.82 M','0.68 M','0.36 M'][i]||'示例':'—',x.requests?['426 K','122 K','76 K'][i]||'示例':'—',x.requests?'64.8%':'—',x.requests?'0.92 s':'—',x.requests?'68.2 tok/s':'—',x.requests?'4':'0'])))+
 card('请求明细',table(['请求 ID','模型','结果','Prefill','TTFT','输出','总耗时','详情'],[['req_demo_a42c',current().name,tag('完成','green'),'0.64 s','0.86 s','326 tokens','5.4 s',button('查看','request-detail','req_demo_a42c','compact')],['req_demo_f821','Nemotron',tag('取消','amber'),'1.0 s','1.22 s','128 tokens','3.7 s',button('查看','request-detail','req_demo_f821','compact')]]));
};
pages.models=()=>heading('模型库','已安装、受支持和辅助模型分别管理。目录扫描后核验格式与能力。',button('重新扫描','scan')+button('添加本地目录','add-dir')+button('下载模型','goto','downloads','primary'))+
 tabs([['installed','已安装模型'],['supported','支持模型目录'],['helpers','草稿与辅助模型']], 'modelTab')+
 (state.modelTab==='helpers'?card('辅助模型',table(['辅助模型','用途','兼容主模型','状态','操作'],[['z-lab/Qwen3.8-27B-DFlash2','DFlash2 草稿','Qwen3.8-27B',tag('未下载'),button('加入下载队列','download','draft-qwen','compact')],['z-lab/gemma-4-26B-A4B-it-DFlash','DFlash 草稿','Gemma 4 26B-A4B',tag('未下载'),button('加入下载队列','download','draft-gemma','compact')],['包含的 MTP head','MTP','Nemotron / Flash Next / GLM',tag('随主模型核验','blue'),button('核验文件','inspect','MTP head','compact')]]))+note('辅助模型不可作为独立聊天模型。草稿格式、许可证和主模型配对单独检查。'):
 `<div class="tf-toolbar"><input class="tf-search" id="model-search" aria-label="搜索模型" placeholder="搜索名称或仓库 ID"><div class="tf-actions">${tag('MLX / Apple Silicon','blue')}${tag('5 个受支持模型族')}</div></div><div class="tf-list-grid" id="model-list">${models.filter((m,i)=>state.modelTab==='supported'||i<3).map(m=>modelCard(m)).join('')}</div>${note('支持模型目录对应官方已列出的 checkpoint。其他量化版本须逐一核验；CUDA / EXL3 仅列为能力参考，不作为本机可加载模型。')}`);
function modelCard(m){return `<div class="tf-card" data-model-card="${m.id}"><div class="tf-row"><h2>${m.name}</h2>${button(state.favorites.has(m.id)?'★':'☆','favorite',m.id,'compact')}</div><div class="tf-model-repo" style="margin-top:8px">${m.repo}</div><div class="tf-chips">${tag(m.quant)}${tag(m.id===state.model&&state.running?'已加载':'未加载',m.id===state.model&&state.running?'green':'')}${tag('文本模型')}</div>${kv('估算文件大小',m.size+' · 示例')}${kv('推测解码',m.draft)}${kv('默认 / API 暴露',m.id===state.model?'默认模型 · 已暴露':'非默认 · 可启用')}<div class="tf-divider"></div><div class="tf-actions">${button(m.id===state.model&&state.running?'卸载 / 停止服务':'加载 / 切换','model-load',m.id,m.id===state.model&&state.running?'':'primary')}${button('配置','model-select',m.id)}${button('更多','model-more',m.id,'compact')}</div></div>`}
pages.downloads=()=>heading('模型下载器','面向国内网络，明确来源、版本、文件校验与模型兼容性。',button('下载源设置','download-settings')+button('自定义仓库','download-custom','','primary'))+
 tabs([['catalog','TensorFold 支持模型'],['tasks','下载任务'],['discover','远端模型发现'],['sources','来源与国内映射']], 'downloadsTab')+
 (state.downloadsTab==='catalog'?`<div class="tf-toolbar"><input class="tf-search" id="download-search" aria-label="搜索支持模型" placeholder="搜索支持模型或 checkpoint"><div class="tf-inline-filters"><select id="download-source" aria-label="下载来源"><option>HF 国内镜像（第三方）</option><option>Hugging Face 官方</option><option>ModelScope 国内</option></select></div></div>`+card('模型目录',table(['模型 / 官方 checkpoint','格式与后端','草稿要求','估算大小','操作'],models.map(m=>[`<div>${m.name}</div><div class="tf-model-repo">${m.repo}</div>`,'MLX · '+m.quant,m.draft,m.size,button('下载','download',m.id,'primary compact')])) )+note('镜像的可达性、revision 与文件一致性在下载前检查。ModelScope 同名仓库不等于同一权重；未验证映射不自动替代。',true):
 state.downloadsTab==='tasks'?card('任务队列',state.jobs.map(j=>`<div class="tf-download-job"><div class="tf-row"><h3>${escapeHtml(j.model)}</h3>${tag(j.canceled?'已取消':j.progress===100?'已校验完成':j.paused?'已暂停':'下载中',j.canceled?'':j.progress===100?'green':j.paused?'amber':'blue')}</div><div class="tf-sub">来源 ${escapeHtml(j.source)} · revision demo-revision · 模拟任务</div><div class="tf-bar"><i style="width:${j.progress}%"></i></div><div class="tf-row"><span class="tf-sub">${j.progress}% · ${j.progress===100?'SHA256 / 文件清单校验通过（演示）':'剩余时间与速率仅在真实下载时采集'}</span><div class="tf-actions">${j.progress<100&&!j.canceled?button(j.paused?'继续':'暂停','job-pause',j.id,'compact')+button('推进演示','job-progress',j.id,'compact')+button('取消','job-cancel',j.id,'danger compact'):button('重试','job-retry',j.id,'compact')}${button('详情','job-detail',j.id,'compact')}</div></div></div>`).join(''))+note('任务设计包含：排队、预检、下载、暂停、续传、校验、完成和失败。来源失败时提示切换，保留可恢复的临时文件；模型文件不在取消时自动删除。'):
 card('下载源与映射',table(['来源','地址 / 接口','权重身份','当前状态'],[['Hugging Face 官方','huggingface.co / snapshot_download','repo + revision + 文件清单',tag('未测试','amber')],['HF 国内镜像','hf-mirror.com · 第三方','保留 HF repo / revision，核验文件',tag('未测试','amber')],['ModelScope 国内','modelscope.cn / snapshot_download','单独 namespace/repo + revision',tag('待建立验证映射','amber')]]))+card('国内仓库映射管理',`${form([select('官方 checkpoint',models.map(x=>x.repo),'map-hf'),field('ModelScope 仓库 ID','','请填写真实国内仓库，不根据名称自动猜测','text','map-ms'),field('revision','main','实施时解析为固定版本','text','map-revision'),select('验证状态',['待核验','配置 / 权重 / MTP / 文件一致性已验证（演示）'])])}<div class="tf-actions" style="margin-top:18px">${button('演示验证映射','map-verify','','primary')}</div>${note('先确认模型架构、量化格式、分片、tokenizer、chat template 与 MTP head，再确认文件哈希或可信权重等价证据。')}`));
pages['model-config']=()=>heading('模型配置','采样、上下文、推测解码与配置档；清楚区分已保存和运行中参数。',button('恢复默认','config-reset')+button('保存配置','save','model','primary'))+
 `<div class="tf-toolbar"><div class="tf-inline-filters"><select id="config-model" aria-label="配置模型">${models.map(m=>`<option value="${m.id}" ${m.id===state.configModel?'selected':''}>${m.name}</option>`).join('')}</select></div><div class="tf-actions">${tag(state.pending?'已保存 · 待重启':'运行配置已同步（示例）',state.pending?'amber':'green')}${button('查看实际启动参数','show-command','','compact')}</div></div>`+
 tabs([['sampling','采样与上下文'],['draft','推测解码'],['profiles','配置档与模板'],['advanced','高级与兼容性']], 'modelConfigTab')+
 (state.modelConfigTab==='sampling'?`<div class="tf-grid two">${card('生成参数',form([field('Temperature','0.7','0 为贪心解码'),field('Top P','0.8'),field('Top K','20'),field('最大生成 tokens','4096'),field('上下文容量','32768','prompt + reply 总容量'),select('默认思考模式',['遵循模型默认','开启 thinking','关闭 thinking']),select('Reasoning effort',['medium','low','high']),field('Thinking budget','8192')]))}${card('模型与 API 标识',`${form([field('显示名称',configCurrent().name),field('API 模型 ID',configCurrent().repo),field('模型别名','local-default'),select('加载策略',['手动加载 / 单模型切换','打开 App 后加载默认模型']),field('模型路径','~/Models/TensorFold/'+state.configModel),field('Draft 模型','auto')])}<div class="tf-divider"></div>${check('设为默认模型')}${check('在 API 模型列表中显示')}${note('显示名、收藏与隐藏由管理层维护。模型启动参数只展示该引擎 / 模型真实支持的字段。')}`)}</div>`:
 state.modelConfigTab==='draft'?`<div class="tf-grid two">${card('Draft & Verify',`${form([select('推测解码',['自动 / 按模型能力','关闭 drafts（serial reference）']),select('Drafter',['auto','none','z-lab/Qwen3.8-27B-DFlash2']),field('MTP drafts 上限','4','模型族专属参数'),select('MTP confidence（仅 CUDA）',['本机 MLX 不适用'])])}${note('每个模型有独立能力门禁，MTP、DFlash 与 context copies 不能互相等同。接收率、轮次与 tokens/round 从真实请求结果采集。')}`)}${card('实际运行状态',`${kv('当前模式','Exact draft verification · 示例')}${kv('Draft / Accepted','1,042 / 819 · 示例')}${kv('接受率','78.6% · 示例')}${kv('验证轮数','264 · 示例')}${kv('Tokens / round','3.10 · 示例')}${kv('Serial 对照','尚未运行')}${button('创建 drafted vs serial 测试','goto','bench','primary')}`)}</div>`:
 state.modelConfigTab==='profiles'?card('配置档与全局模板',`${table(['配置档','用途','API 虚拟模型 ID','状态','操作'],[['日常编码','temperature 0.7 · 16K 回复','qwen27-coding',tag('示例配置档','blue'),button('应用','apply-profile','日常编码','compact')],['低延迟对话','4K 回复 · 无思考','qwen27-fast',tag('未应用'),button('应用','apply-profile','低延迟对话','compact')],['精确对照','关闭 drafts · 固定 seed','qwen27-serial',tag('测试配置'),button('应用','apply-profile','精确对照','compact')]])}<div class="tf-actions" style="margin-top:18px">${button('新建配置档','profile-new','','primary')}${button('另存为全局模板','profile-new','template')}${button('导入 JSON / Recipe','profile-import')}${button('导出当前配置','export-profile')}</div>${note('配置档和虚拟模型别名属于管理层适配，不依赖修改 TensorFold 核心。模板应用前检查不支持字段；不会把 oMLX 专属参数直接传入上游。')}`):
 card('兼容性检查',table(['能力','TensorFold 本机状态','处理'],[['Temperature / Top P / Top K',tag('CLI 原生支持','green'),'保存 → 新请求默认 / 重启生效按适配器规则'],['Min P / Presence penalty / Repetition penalty',tag('当前未证实支持','amber'),'不作为已可用参数发送'],['模型 TTL / 收藏 / 隐藏 / 虚拟 Profile',tag('管理层新增','blue'),'不直接映射引擎参数'],['TurboQuant / ANE / oQ A8 / SpecPrefill',tag('oMLX 引擎专属','amber'),'保留能力说明，不伪装成本机可用'],['VLM / Embedding / Reranker / Audio',tag('当前 TensorFold 未证实支持','amber'),'不允许用文本模型冒充这些端点']]))+note('所有高级参数以选定版本和模型能力为准。支持矩阵变化可由适配器更新，无需重写全部页面。'));
pages.cache=()=>heading('缓存管理','查看缓存用量、命中、快照和各模型缓存；清理前确认范围。',button('刷新统计','refresh','缓存')+button('缓存探测','cache-probe'))+
 tabs([['engine','引擎内存与 Prompt cache'],['disk','快照与磁盘缓存'],['models','各模型缓存']], 'cacheTab')+
 `<div class="tf-metrics">${metric('MLX 活动内存',state.running?'24.8':'—','GB','health.memory.active')}${metric('MLX allocator cache',state.running?'3.2':'—','GB','health.memory.cache · 非前缀命中')}${metric('峰值内存',state.running?'31.1':'—','GB','health.memory.peak')}${metric('缓存输入 tokens','1.85 M','','网关累计 · 示例')}</div>`+
 (state.cacheTab==='engine'?`<div class="tf-grid two">${card('前缀与上下文缓存',`${kv('Prompt cache 预算','8 GB · 示例配置')}${kv('保留会话前缀','64 · 示例')}${kv('命中率','64.8% · 示例')}${kv('命中 tokens / 输入 tokens','1.85 M / 2.86 M')}${kv('Checkpoint hit / miss / eviction','84 / 16 / 3 · 日志汇总示例')}<div class="tf-divider"></div>${button('清理当前模型缓存','cache-clear','当前模型内存与前缀缓存','danger')}${note('TensorFold 当前无已核验的 HTTP 清理端点（oMLX 已有 hot / SSD clear）。管理层可能需排空请求并重启引擎，确认弹窗会说明停机和影响范围。')}`)}${card('配置与来源',`${form([field('Prompt cache GiB','8'),field('MLX cache 上限 GiB','3.2'),field('Snapshot 目录','~/Library/Application Support/TensorFold Manager/cache/snapshots'),field('最大快照数量','64')])}<div class="tf-actions" style="margin-top:17px">${button('保存缓存配置','save','cache','primary')}</div>${note('allocator cache、Prompt cache、checkpoint / spill 是不同统计口径。未知值显示未采集，不使用 0 代替。')}`)}</div>`:
 state.cacheTab==='disk'?`<div class="tf-grid two">${card('快照 / Spill 存储',`${kv('快照根目录','~/Library/Application Support/TensorFold Manager/cache')}${kv('当前大小 / 预算','4.6 / 32 GB · 示例')}${kv('文件数','326 · 示例')}${kv('最后写入','10:27:42 · 示例')}${kv('索引状态',tag('管理层设计','blue'))}<div class="tf-bar"><i style="width:15%"></i></div><div class="tf-actions">${button('查看文件清单','cache-manifest')}${button('清理快照','cache-clear','当前模型快照 / spill','danger')}</div>`)}${card('oMLX Hot / SSD 缓存对照',`${kv('Hot RAM cache',tag('不能直接复用实现','amber'))}${kv('SSD block cache',tag('需独立适配与验证','amber'))}${kv('GDN sidecar / ANE compile cache',tag('当前引擎未证实','amber'))}${note('原型保留容量、目录、清理与诊断流程。实际支持的存储层以 TensorFold 当前版本为准，不假设已有 oMLX 的分页缓存。')}`)}</div>`:
 card('按模型查看',table(['模型','输入 tokens','cached tokens','命中率','快照大小','状态','操作'],models.map(m=>[m.name,m.requests?'1.82 M':'—',m.requests?'1.18 M':'—',m.requests?'64.8%':'—',m.requests?'4.6 GB · 示例':'未采集',tag(m.id===state.model?'当前引擎':'历史汇总',m.id===state.model?'blue':''),button('清理','cache-clear',m.name+' 缓存','danger compact')]))));
pages.server=()=>heading('服务器与目录','主机信息、监听端口、模型路径和 macOS App 生命周期。',button('导出诊断信息','export-diagnostic')+button('保存设置','save','server','primary'))+
 `<div class="tf-grid two">${card('主机信息',`${kv('主机名','Mac Studio · 示例')}${kv('处理器 / GPU','Apple Silicon · 示例')}${kv('系统','macOS · 示例')}${kv('统一内存','256 GB · 示例')}${kv('Python / MLX','3.11 / 0.32.2 · 示例')}${kv('架构 / 后端','arm64 / MLX Metal')}${kv('可用磁盘空间','1.24 TB · 示例')}${kv('推理进程状态',state.running?tag('运行中 · PID 48271','green'):tag('已停止','amber'))}`)}${card('端口与网络',`${form([field('API 网关监听地址','127.0.0.1','对外访问须配置认证'),field('API 网关端口','8080'),field('管理服务端口','8081'),field('引擎内部端口','8082','只允许 loopback'),select('访问范围',['仅本机（默认）','局域网（需确认与认证）']),field('服务别名','tensorfold-local')])}${note('端口分工为设计建议：管理层独立运行，API 网关保持稳定，后端引擎可重启。端口冲突预检后才启动。')}`)}</div>`+
 card('模型与数据目录',`${table(['用途','目录（示例）','状态','操作'],[['主模型目录','~/Models/TensorFold',tag('已配置','blue'),button('编辑','directory-edit','模型目录','compact')],['辅助 / 草稿模型','~/Models/TensorFold/drafters',tag('已配置','blue'),button('编辑','directory-edit','草稿目录','compact')],['下载临时目录','~/Models/TensorFold/.downloads',tag('模拟'),button('编辑','directory-edit','下载目录','compact')],['日志 / 统计 / 聊天','~/Library/Application Support/TensorFold Manager',tag('管理层设计','blue'),button('查看说明','directory-edit','App 数据目录','compact')]])}<div class="tf-actions" style="margin-top:15px">${button('新增模型目录','add-dir')}${button('重新扫描模型','scan')}</div>${note('更换目录不移动或删除已有模型。目录扫描结果与引擎格式兼容性独立核验。')}`)+
 card('App 行为',form([select('关闭窗口时',['隐藏窗口，服务继续运行','停止服务并退出']),select('退出 App 时',['有在途请求则提示等待 / 取消','完成当前请求后退出']),select('打开 App 时',['只打开管理界面','自动启动默认模型']),select('登录系统时',['不自动启动','自动启动 App']),select('异常退出后',['显示错误，手动重试','有限重启并显示次数']),select('日志与统计保留',['30 天（设计默认）','7 天','90 天']),select('界面语言',['简体中文','English','跟随系统']),select('界面主题',['浅色','跟随系统（设计）'])]));
pages['engine-config']=()=>heading('推理框架配置','全局默认、调度、内存预算和引擎参数；按版本能力显示。',button('恢复默认','config-reset')+button('保存配置','save','engine','primary'))+
 `<div class="tf-grid two">${card('后端与调度',`${form([select('执行后端',['auto（macOS → MLX）','mlx','cuda（本机不可用）']),select('并行通道',['auto · 按内存 admission','1','2','4','8']),field('默认上下文 tokens','32768'),field('最大生成 tokens','4096'),field('预热策略','遵循引擎默认'),select('调度状态采集',['网关计数 + 引擎 health','仅引擎 health'])])}${note('MLX auto 最多 8 通道且受内存与模型约束；配置上限不等于当前实际并发。')}`)}${card('内存与 Prompt cache',`${form([field('Prompt cache 预算 GiB','8'),field('Checkpoint slots','64'),field('MLX cache 上限 GiB','3.2'),field('Spill 预算 GiB','32'),select('内存压力策略',['停止新请求并报告','仅报告（设计选项）']),select('日志等级',['INFO','DEBUG','WARNING','ERROR'])])}${note('MLX active/cache/peak 来自 health。管理层的 admission 策略与原生调度分别标明来源。')}`)}</div>`+
 card('默认采样与推测解码',`${form([field('Temperature','0.7'),field('Top P','0.8'),field('Top K','20'),select('Drafts 默认',['启用 / 按模型支持','关闭 drafts']),select('Thinking 默认',['模型默认','开启','关闭']),select('Reasoning effort',['medium','low','high'])])}${note('优先级建议：单次请求参数 → 模型配置档 → 全局默认。只有该版本 CLI 支持的参数会传给引擎。')}`)+
 card('能力感知参数',table(['参数 / 能力','MLX','CUDA','本机处理'],[['KV dtype int8 / int4','不支持','Flash Next 特定路径','禁用并解释'],['Tensor parallel / rank / master','不支持','按模型族限制','本机不展示可用态'],['Snapshot / checkpoint / spill','CLI 原生','按后端能力','保存目录 / slots / 预算'],['Lane kernels / SSD experts / PLE on SSD','CLI 已列出，按模型支持','后端受限','显示能力与模型格式门禁'],['TurboQuant / ANE / GDN / MoE offload','oMLX 专属','不适用','适配说明中保留，不发送']]),button('查看适配矩阵','goto','capabilities','compact'));
pages.api=()=>heading('API 与集成','OpenAI 兼容端点、模型列表、接入示例和开发工具配置。',button('连通性测试（模拟）','api-test')+button('复制 Base URL','copy','http://127.0.0.1:8080/v1'))+
 tabs([['endpoints','API 端点'],['clients','客户端接入'],['tools','MCP 与工具']], 'apiTab')+
 (state.apiTab==='endpoints'?card('端点清单',`${kv('公开 Base URL','http://127.0.0.1:8080/v1')}${kv('内部引擎（不对外暴露）','http://127.0.0.1:8082')}${kv('认证',tag('管理网关 Bearer key（设计）','blue'))}${table(['方法','路径','用途','支持来源'],[['GET','/health','服务 / warming / model / memory',tag('上游原生','green')],['GET','/v1/models','当前引擎模型 ID / aliases',tag('上游原生','green')],['POST','/v1/chat/completions','文本多轮 / SSE / tools',tag('上游原生','green')],['POST','/v1/completions','文本补全',tag('上游原生','green')],['GET','管理层 statistics API','累计 / 模型 / 任务状态',tag('需要新增','blue')],['POST','/v1/embeddings / rerank / images / audio','非文本模型接口',tag('当前未证实支持','amber')]])}<div class="tf-divider"></div><h3>curl 接入示例</h3><div class="tf-code"><pre>curl http://127.0.0.1:8080/v1/chat/completions \
  -H 'Authorization: Bearer YOUR_API_KEY' \
  -H 'Content-Type: application/json' \
  -d '{"model":"local-default","messages":[{"role":"user","content":"你好"}],"stream":true}'</pre></div>${button('复制示例','copy-curl')}`):
 state.apiTab==='clients'?`<div class="tf-list-grid">${['Codex / OpenAI SDK','OpenCode','Claude Code','Copilot CLI','OpenClaw / Hermes / Pi','Continue / IDE','自定义 OpenAI 客户端'].map((name,i)=>card(name,`${kv('Base URL','http://127.0.0.1:8080/v1')}${kv('模型映射','local-default')}${kv('状态',tag(i===2?'需 Anthropic 协议桥接':'未连通测试','amber'))}${button('生成配置示例','client-config',name,'compact')}${note(i===2?'TensorFold 原生为 OpenAI API；Claude Code 接入需独立协议桥接，不能仅更改 URL。':'配置模板不能替代真实工具调用、流式和多轮验收。')}`)).join('')}</div>`:
 card('MCP / 文档 / 搜索适配',`${form([field('MCP 配置文件','管理层工具注册表（设计）'),select('工具暴露策略',['只在内置聊天启用','经确认后开放给 API']),select('文档转文本',['管理层 MarkItDown 适配（待验证）','禁用']),select('Web 搜索',['未配置','SearXNG','Brave Search','其他连接器'])])}<div class="tf-divider"></div>${table(['能力','实现归属','状态'],[['Tool calling / tool_choice','TensorFold chat API',tag('原生协议','green')],['执行工具 / MCP servers','管理层编排',tag('需要新增','blue')],['上传文档 / PDF 转文本','管理层文档适配',tag('需要新增','blue')],['视觉输入 / 音频','模型与引擎',tag('当前未证实支持','amber')]])}${button('保存集成配置','save','integrations','primary')}${note('工具协议支持不代表工具已执行；原型不访问外部 MCP、不上传文件、不发送搜索请求。')}`));
pages.auth=()=>heading('认证与密钥','管理登录、推理 API Key 与模型下载凭据各自隔离。',button('安全策略','auth-policy')+button('新建子密钥','key-new','','primary'))+
 `<div class="tf-grid two">${card('管理界面认证',`${form([select('管理登录方式',['本机 App 安全会话','用户名与密码（局域网设计）']),field('管理用户名','local-admin'),select('会话过期',['30 分钟','8 小时','关闭 App 时']),select('访问策略',['仅本机','局域网访问必须登录'])])}${note('不将管理员凭据拼入自动登录 URL。真正认证由管理层提供，当前原型未登录真实服务。')}`)}${card('推理 API 认证',`${kv('主密钥','tf_demo_••••••••_readonly')}${kv('密钥存储','macOS Keychain（设计建议）')}${kv('认证模式',tag('必须携带 Bearer key','green'))}${kv('上游认证能力',tag('需管理网关验证','blue'))}<div class="tf-actions" style="margin-top:14px">${button('轮换主密钥','key-rotate')}${button('保存认证策略','save','auth','primary')}</div>${note('管理 Cookie、推理 key、下载 token 和上传 token 不是同一凭据。原型只生成显式 demo 字符串。')}`)}</div>`+
 card('子密钥',table(['名称','密钥（遮罩）','权限','状态','调用量','操作'],state.keys.map((k,i)=>[escapeHtml(k.name),k.masked,k.permission,tag(k.status,k.status==='启用'?'green':'amber'),k.usage,button(k.status==='启用'?'停用':'启用','key-toggle',i,'compact')+button('撤销','key-revoke',i,'danger compact')])) )+
 card('下载与上传凭据',`${table(['用途','状态','存储','操作'],[['Hugging Face token',tag('未配置'),'Keychain · 不进 Git',button('配置演示','token-config','Hugging Face','compact')],['ModelScope token',tag('未配置'),'Keychain · 不进日志',button('配置演示','token-config','ModelScope','compact')],['GitHub 检查更新','公开 API 可不带 token','默认不要求权限',button('检查更新','update-check','','compact')],['上传凭据',tag('未配置'),'单独授权外部写入',button('配置演示','token-config','上传','compact')]])}${note('请勿在设计原型中输入真实凭据。模拟密钥不会保存到持久化存储，刷新页面即重置。',true)}`);
pages.updates=()=>{
 const labels=['未检查','发现更新（模拟）','下载与隔离环境准备','兼容性检查','冒烟验证完成','新版本已启用（模拟）'];
 return heading('版本与更新','管理 App、TensorFold 引擎和运行时分别版本化，跟随上游而保留回退。',button('GitHub 一键检查','update-check','','primary'))+
 `<div class="tf-grid two">${card('TensorFold 主引擎',`${kv('当前版本',state.engineVersion+' · 示例安装')}${kv('安装来源','github.com/ashhart/TensorFold')}${kv('当前 commit','示例 revision，实施时读回实际 SHA')}${kv('上游更新入口','tensorfold update --check / update')}${kv('最新版本',state.updateStage?'0.3.6.3 · 模拟候选':'未检查')}${kv('发布日期','只从 GitHub 读回，不推测')}${kv('当前状态',tag(state.updateFail?'验证失败 · 保留旧引擎':labels[state.updateStage],state.updateFail?'red':state.updateStage===5?'green':'blue'))}<div class="tf-divider"></div><div class="tf-actions">${button('查看上游变更','upstream-info')}${state.updateStage>0&&state.updateStage<5?button('继续升级演示','update-next','','primary'):''}${button('回退上一版本','update-rollback')}</div>`)}${card('管理 App 与依赖',`${kv('TensorFold Manager','0.2.0 · 交互原型')}${kv('App GitHub','alickfine/TensorFold-Manager')}${kv('Python','3.11 · 示例')}${kv('MLX','0.32.2 · 示例')}${kv('适配器','TensorFold CLI / health / completion v1')}${kv('自动策略','检查并提示，手动确认激活（建议）')}${note('不依赖修改上游核心；CLI 参数、health schema、SSE 与指标结构分别测试。未知版本可显示“尚未验证”，不强行启动。')}`)}</div>`+
 card('升级与回退流程',`${['检查 GitHub release / tag / commit','创建隔离安装环境，保留旧版本','探测 CLI / 模型支持 / health schema','运行 health、SSE、tool schema 与统计冒烟验证','排空请求并切换，读回实际引擎版本'].map((t,i)=>`<div class="tf-step ${state.updateStage>i?'done':''}"><b>${state.updateStage>i?'✓':i+1}</b><div>${t}<p>${['显示来源与变更清单，不直接覆盖当前环境','不安装到 oMLX 环境，不改模型权重','适配器能力表决定界面可用字段','兼容检查通过才能激活；真实推理验证需选定模型','失败保持旧版本，必要时提供回退与诊断'][i]}</p></div></div>`).join('')}<div class="tf-actions" style="margin-top:17px">${button('预览验证失败','update-failure')}${button('查看兼容矩阵','goto','capabilities')}</div>`)+
 card('macOS App 安装与发行',`${kv('发行目标','GitHub Releases · alickfine/TensorFold-Manager')}${kv('安装包','TensorFold-Manager-&lt;version&gt;-macOS-arm64.dmg')}${kv('安装方式','打开 DMG → 将 App 拖入应用程序')}${kv('架构','Apple Silicon arm64 · Intel 未列入首版')}${kv('运行时','计划提供隔离引擎环境，不依赖 oMLX 的 Python')}${kv('SHA256 / 签名 / 公证','正式打包时读回；当前未构建')}<div class="tf-actions">${button('查看发布资产设计','release-assets')}</div>${note('当前 GitHub 只有源码与原型，尚无可安装 DMG。Release 必须同时注明 App / 引擎版本、macOS 要求、校验值及签名公证状态。')}`)+
 card('版本历史（示例）',table(['版本','环境','结果','操作'],[[state.engineVersion,'当前环境',tag('当前运行（演示）','green'),button('详情','inspect','当前引擎版本','compact')],[state.lastVersion,'保留的隔离环境',tag('可回退（演示）','blue'),button('回退','update-rollback','','compact')]]));
};
const logs=[['INFO','10:24:01','manager','[demo] API gateway bound to 127.0.0.1:8080'],['INFO','10:24:02','engine','[demo] Loading Vontra/Qwen3.8-27B-MLX-4bit'],['INFO','10:24:16','engine','[demo] Health ready · memory active=24.8GB cache=3.2GB'],['INFO','10:26:42','request','[demo] req_a42c prompt=2048 cached=1327 completion=326 TTFT=0.86'],['WARNING','10:27:14','download','[demo] Domestic mapping not yet verified; no replacement made'],['ERROR','10:27:45','adapter','[demo] Unsupported parameter rejected in validation preview'],['INFO','10:28:02','engine','[demo] tok/s=72.4 accepted=819 drafted=1042']];
pages.logs=()=>heading('运行日志','引擎、网关、下载和更新日志集中查看，正文与凭据默认脱敏。',button('刷新','refresh','日志')+button('导出脱敏日志','export-logs'))+
 `<div class="tf-toolbar"><div class="tf-inline-filters"><select id="log-file" aria-label="日志文件"><option>当前 server.log</option><option>server.1.log（历史）</option><option>download.log</option><option>update.log</option></select><select id="log-level" aria-label="日志级别">${[['all','全部等级'],['INFO','INFO'],['WARNING','WARNING'],['ERROR','ERROR']].map(([v,t])=>`<option value="${v}" ${state.logLevel===v?'selected':''}>${t}</option>`).join('')}</select><select aria-label="日志行数"><option>最后 200 行</option><option>最后 1000 行</option><option>最后 10000 行</option></select></div><input class="tf-search" id="log-search" aria-label="搜索日志" value="${escapeHtml(state.logQuery)}" placeholder="搜索日志 / request ID"></div>`+
 card('日志内容',`<div id="log-output" class="tf-log">${filteredLogs()}</div><div class="tf-actions" style="margin-top:15px">${check('自动滚动')}${check('自动刷新（原型不轮询）',false)}${button('预览启动失败','startup-error','','compact')}${button('查看诊断信息','export-diagnostic','','compact')}</div>${note('按日志文件、等级和文本查询。历史文件读取由管理层校验路径，日志导出不含真实请求正文、密钥和下载 token。')}`);
function filteredLogs(){const filtered=logs.filter(l=>(state.logLevel==='all'||l[0]===state.logLevel)&&l.join(' ').toLowerCase().includes(state.logQuery.toLowerCase()));return filtered.length?filtered.map(l=>`<div>${escapeHtml(l[1]+'  '+l[0].padEnd(7)+' ['+l[2]+'] '+l[3])}</div>`).join(''):'无匹配日志';}
pages.bench=()=>heading('基准测试','吞吐、上下文极限、准确性与 drafted / serial 对照，全部任务可追踪。',button('历史结果','bench-history')+button('导出结果','export-bench'))+
 tabs([['throughput','吞吐与延迟'],['context','上下文压力'],['accuracy','准确性 / 一致性'],['compare','Drafted / Serial 对照'],['ane','ANE 调优（能力门禁）']], 'benchTab')+
 `<div class="tf-grid two">${card('测试配置',`${form([select('目标',['本机 TensorFold','外部 OpenAI 兼容端点']),select('测试模型',models.map(m=>m.name),'bench-model',current().name),field('输入长度 tokens',state.benchTab==='context'?'4096,8192,16384,32768':'512,2048,8192'),field('输出长度 tokens','512'),field('并发 / Batch','1,2,4'),field('重复次数','3'),select('缓存条件',['Cold 与 Warm 分开记录','Cold','Warm']),field('Seed','42')])}${state.benchTab==='accuracy'?note('准确性包含用户测试集；drafted / serial 的输出一致性单独评估，不将 token 一致等同事实正确。'):state.benchTab==='context'?note('逐档增加上下文，记录 TTFT、prefill、decode、总耗时、内存和失败；遇内存压力停止，不以 OOM 作为必做步骤。'):note('同一模型、权重、seed、采样和缓存条件进行比较。峰值 decode 不等于端到端任务加速。')}<div class="tf-actions" style="margin-top:18px">${button('开始模拟测试','bench-start','','primary')}${button('取消模拟任务','bench-cancel')}</div>`)}${card('任务状态与结果',state.benchmarkDone?`${tag('模拟任务已完成','green')}<div class="tf-result-highlight">固定模型 / 输入条件 · 以下全部为演示结果</div>${kv('测试耗时','00:38 · 示例')}${kv('平均 TTFT','0.86 s')}${kv('Prefill','2,384 tok/s')}${kv('Decode','72.4 tok/s')}${kv('P95 总耗时','8.12 s')}${kv('峰值内存','31.1 GB')}${kv('输出一致性','待真实对照验证')}`:`<div class="tf-empty">尚未运行测试<br><small>点击“开始模拟测试”查看任务与结果布局</small></div>${note('原型不会向本机 oMLX 或 TensorFold 发送基准请求。外部候选（如 oMLX）与本机引擎应采用一致输入，并记录各自版本。')}`)}</div>`+
 card('结果比较（示例）',table(['条件','TTFT','Prefill','Decode','总耗时','峰值内存','任务成功'],[['2K / 512 · cold · drafts','0.86 s','2,384 tok/s','72.4 tok/s','8.12 s','31.1 GB',tag('演示','blue')],['2K / 512 · cold · serial','0.81 s','2,410 tok/s','24.6 tok/s','21.62 s','28.4 GB',tag('演示','blue')],['8K / 512 · warm · drafts','0.42 s','缓存命中','71.8 tok/s','7.55 s','34.2 GB',tag('演示','blue')]]))+note('ANE tuning 属于 oMLX 专属，不显示为 TensorFold 可执行测试。准确性数据集、外部客户端和真实工具调用另行验收。');
pages.chat=()=>heading('内置聊天','用当前服务进行多轮文本对话，查看推理、工具调用和每轮性能。',button('导出对话','chat-export')+button('新建对话','chat-new'))+
 `<div class="tf-chat-layout"><div class="tf-chat-sidebar"><h3>会话</h3><div class="tf-chat-list"><button class="active" data-action="chat-history" data-value="current">当前对话<br><span class="tf-sub">${current().name}</span></button><button data-action="chat-history" data-value="tools">工具调用演示<br><span class="tf-sub">只展示协议结构</span></button></div><div class="tf-divider"></div><div class="tf-sub">会话默认本机保存。是否持久化正文与保留期限待验收确认。</div></div><div class="tf-chat-main"><div class="tf-row"><h3>${current().name}</h3>${tag(state.running?'服务就绪 · 演示':'服务已停止',state.running?'green':'amber')}</div><div class="tf-messages" id="chat-messages">${chatMessages()}</div><div class="tf-composer"><textarea id="chat-input" aria-label="聊天输入" placeholder="输入消息；这是模拟对话，不会请求真实模型" ${state.chatBusy?'disabled':''}></textarea><div class="tf-actions"><span class="tf-sub">文本模式 · 示例数据</span><div class="tf-actions">${button('文档转文本','chat-document','','compact')}${button(state.chatBusy?'停止生成':'发送消息',state.chatBusy?'chat-stop':'chat-send','','primary compact')}</div></div></div></div><div class="tf-chat-settings"><h3>对话参数</h3><div class="tf-form-grid">${select('模型',models.slice(0,3).map(m=>m.name),'chat-model',current().name)}${field('Temperature','0.7')}${field('Top P','0.8')}${field('Max tokens','4096')}${select('Thinking',['模型默认','开启','关闭'])}${select('工具模式',['关闭工具','展示模拟工具调用'])}</div><div class="tf-field"><label for="system-prompt">System prompt</label><textarea id="system-prompt">你是一个清晰、可靠的助手。</textarea></div>${note('文本聊天 / reasoning / tools 按真实模型能力显示。视觉与音频不假装已支持。')}<div class="tf-sub">生成后展示 TTFT、输入/输出 tokens、decode、总耗时、draft 接受率与 finish reason。</div></div></div>`;
function chatMessages(){const intro=`<div class="tf-message"><div class="tf-avatar">Tƒ</div><div class="tf-message-body">你好，这里是 TensorFold 的本地聊天工作区。\n你可以查看多轮对话、生成参数和每轮推理统计。<details class="tf-disclosure"><summary>展开 reasoning 演示</summary><div>思考内容独立折叠，和最终回答分开展示。这里是布局样例。</div></details><div class="tf-code"><pre>// Markdown 代码块预览
const client = new OpenAI({baseURL: "http://127.0.0.1:8080/v1"});</pre></div><div class="tf-sub">支持规划：Markdown、代码高亮、公式、HTML 清理与工具调用卡片。</div><small>设计演示 · 未连接真实模型</small></div></div>`;return intro+state.chatHistory.map(m=>`<div class="tf-message"><div class="tf-avatar">${m.role==='user'?'你':'Tƒ'}</div><div class="tf-message-body">${escapeHtml(m.text)}${m.role==='assistant'?'<small>示例：TTFT 0.86s · 输入 128 / 输出 64 tokens · 72.4 tok/s · finish=stop</small>':''}</div></div>`).join('');}
pages['model-tools']=()=>heading('量化与上传','借鉴 oMLX 的模型维护流程；输出是否能加载由 TensorFold 格式校验决定。',button('任务记录','tool-history'))+
 tabs([['quantize','模型量化'],['upload','模型上传'],['convert','文件检查与 Sidecar'],['tasks','量化 / 上传任务']], 'toolsTab')+
 (state.toolsTab==='quantize'?`<div class="tf-grid two">${card('量化任务配置',`${form([select('源模型',models.map(m=>m.name)),select('量化后端',['MLX 工具适配（待验证）','oQ 工具（oMLX 专属，待兼容验证）']),select('目标位宽',['4-bit','6-bit','8-bit','混合位宽（需模型格式支持）']),select('Group size',['64','32','128']),select('计算 dtype',['bfloat16','float16']),field('输出目录','~/Models/TensorFold/quantized')])}<div class="tf-divider"></div>${check('保留 tokenizer、配置、模板与 MTP 文件')}${button('估算 / 预检演示','quantize-preflight','','primary')}`)}${card('兼容性门禁',`${kv('oMLX oQ 输出',tag('不能直接保证兼容','amber'))}${kv('TensorFold 支持格式','按模型族 / bit / group 核验')}${kv('MTP head','保留且检查配对')}${kv('原始权重','不原地覆盖')}${note('量化功能是管理层工具适配，非 TensorFold 已有管理 API。若输出格式未通过核验，不能作为可加载模型。敏感度 / imatrix / A8 专属字段仅在适配验证后启用。')}`)}</div>`:
 state.toolsTab==='upload'?card('上传到 Hugging Face',`${form([select('本地模型',models.map(m=>m.name)),field('目标仓库','your-account/model-name','仅示例，不发起外部写入'),select('仓库可见性',['私有（建议）','公开']),field('README 来源','自动生成模型说明（设计）')])}<div class="tf-divider"></div>${check('上传前展示文件清单与总大小')}${check('排除密钥、日志、聊天与临时缓存')}${button('预览上传清单','upload-preview','','primary')}${note('真正上传需要用户确认仓库、可见性和文件范围。上传任务有进度、取消、重试与结果读回；原型不上传任何文件。',true)}`):
 card('模型文件检查',`${table(['文件组','检查项','示例状态'],[['config.json / generation_config','架构 / 模型族 / bit / group',tag('待扫描','amber')],['safetensors / index','分片完整性 / 文件哈希',tag('待扫描','amber')],['tokenizer / chat template','词表与模板一致性',tag('待扫描','amber')],['MTP / drafter sidecar','模型族与辅助权重配对',tag('待扫描','amber')],['LICENSE / notices','权重与 draft 许可条件',tag('待核验','amber')]])}${button('模拟检查','inspect','文件组校验','primary')}${note('oMLX MTPLX sidecar 导入不等于 TensorFold 支持该格式；仅在确认格式后实现对应转换。')}`));
const capabilityRows=[
 ['服务启停 / 重启 / 模型切换','管理层新增','进程监管 + readiness + 错误恢复','服务配置 / 模型库'],
 ['模型库 / 多目录 / 默认 / 收藏 / 隐藏','管理层新增','CLI info + 本地扫描 + 元数据','模型库'],
 ['HF / 国内镜像 / ModelScope 下载','管理层新增','任务队列、revision、续传、文件核验','模型下载器'],
 ['通用采样 / 上下文 / thinking','上游原生','CLI 支持字段 + 版本能力表','模型配置'],
 ['MTP / DFlash / Draft & Verify','上游原生','特定模型能力，不通用','模型配置'],
 ['Profile / Template / Recipe / 虚拟别名','管理层新增','校验字段后应用 / 网关映射','模型配置'],
 ['总计 / Session / 各模型用量与请求','管理层新增','网关请求采集 + runtime/speculative','统计与用量'],
 ['Health / active / cache / peak','上游原生','health + 引擎 warming 状态','运行总览 / 缓存'],
 ['Prompt cache / checkpoint / spill','上游原生','CLI 参数 / 日志，按版本核验','缓存管理'],
 ['Hot / SSD block cache / GDN','引擎专属','oMLX 实现不能直接等同','缓存管理 / 能力门禁'],
 ['端点 / API Key / 管理认证 / 子 key','管理层新增','OpenAI 原生端点 + 独立认证网关','API / 认证'],
 ['Github 版本 / 检查 / 升级 / 回退','管理层新增','上游 update --check / update + 隔离适配和回退','版本与更新'],
 ['服务器 / 端口 / 目录 / 启动行为','管理层新增','设置生效状态 + 冲突预检','服务器与目录'],
 ['当前 / 历史日志 / 过滤 / 导出','管理层新增','stdout/stderr 汇总 + 脱敏','运行日志'],
 ['吞吐 / 上下文 / 准确性 / 对照测试','管理层新增','OpenAI 请求 harness + 可追踪任务','基准测试'],
 ['多轮聊天 / SSE / reasoning / tool schema','上游原生','聊天 UI、会话、工具编排需新增','内置聊天'],
 ['MCP / Web 搜索 / 文档转文本','管理层新增','独立连接器，逐项验收','API 与集成'],
 ['模型量化 / HF 上传 / 文件检查','管理层新增','外部工具、格式门禁、上传确认','量化与上传'],
 ['DMG / GitHub Release / 校验 / 签名与公证状态','管理层新增','macOS App 打包与发行验收','版本与更新'],
 ['Dashboard 布局 / 导入导出 / 语言','管理层新增','本地工作台偏好','总览 / 设置'],
 ['ANE / TurboQuant / oQ A8 / SpecPrefill','引擎专属','本机 TensorFold 未证实这些实现','模型配置 / 能力门禁'],
 ['Embedding / Reranker / VLM / Diffusion / Audio','未证实支持','当前不开放相应推理接口','能力说明'],
 ['集群 / Tensor Parallel / 分布式缓存','引擎专属','CUDA CLI 部分支持；不等于完整集群控制台','能力说明']
];
pages.capabilities=()=>heading('功能适配表','oMLX 管理流程全量对照；真实能力、管理层扩展与引擎专属功能有据可查。',button('导出适配清单','export-capabilities'))+
 `<div class="tf-grid three">${card('原生能力',`<div class="tf-value">${capabilityRows.filter(r=>r[1]==='上游原生').length}</div><div class="tf-sub">CLI、health、OpenAI 协议与模型推测解码</div>`)}${card('管理层新增',`<div class="tf-value">${capabilityRows.filter(r=>r[1]==='管理层新增').length}</div><div class="tf-sub">UI、任务、认证、统计、工具和升级管理</div>`)}${card('兼容性门禁',`<div class="tf-value">${capabilityRows.filter(r=>['引擎专属','未证实支持'].includes(r[1])).length}</div><div class="tf-sub">展示边界与原因，不冒充可用功能</div>`)}</div><div style="margin-top:18px">${tabs([['all','全部功能'],['native','上游原生'],['manager','管理层新增'],['gated','引擎专属 / 待核验']], 'capTab')}</div>`+
 card('覆盖矩阵',table(['功能领域','能力归属','适配方式 / 边界','原型位置'],capabilityRows.filter(r=>state.capTab==='all'||r[1]===({'native':'上游原生','manager':'管理层新增','gated':'引擎专属'}[state.capTab])||(state.capTab==='gated'&&r[1]==='未证实支持')).map(r=>[r[0],tag(r[1],r[1]==='上游原生'?'green':r[1]==='管理层新增'?'blue':'amber'),r[2],r[3]])))+
 card('取证与持续适配',`${kv('参考','本机 oMLX bundle 管理源码 + TensorFold 官方代码')}${kv('TensorFold 证据日期','2026-09-29 · 主分支会变化')}${kv('实施前','固定 commit / 读取实际版本 / 兼容性回归')}${kv('适配边界','不 fork 核心、不修改已有 oMLX、不混用凭据')}<div class="tf-note">本页说明原型覆盖范围，不表示功能已真实实施。所有需要新增的模块均需服务端设计、真实路径验证与最终验收。</div>`);

function serviceAction(action){
 if(action==='start'){state.running=true;state.pending=false;render();toast('演示：预检 → 加载模型 → health ready，服务已启动');return}
 dialog(action==='stop'?'停止推理服务？':'重启推理服务？',`${note('示例：有 1 个在途请求。先暂停接收新请求，再完成当前请求。停止后管理界面仍保持可用。',true)}${select('处理方式',['等待在途请求完成（建议）','立即取消在途请求（演示）'])}${kv('影响模型',current().name)}${kv('API 影响','暂停接收新请求 / 重启窗口')}`,action==='stop'?'确认停止（模拟）':'确认重启（模拟）',()=>{state.running=action!=='stop';state.pending=false;render();toast(action==='stop'?'演示：服务已停止，管理界面继续可用':'演示：服务重启，配置已应用')});
}
function saveSettings(area){saveForm();state.pending=true;render();toast('演示：'+({model:'模型配置',server:'服务器设置',engine:'推理参数',cache:'缓存设置',auth:'认证策略',integrations:'集成设置'}[area]||'设置')+'已保存，待重启生效；未写入真实配置')}
function download(id){const m=models.find(m=>m.id===id);const name=m?.name||(id==='draft-gemma'?'Gemma DFlash':'Qwen DFlash2');const source=$('#download-source')?.value||'HF 国内镜像（第三方）';dialog('确认下载 '+name,`${kv('官方仓库',m?.repo||name)}${kv('来源',escapeHtml(source))}${field('固定 revision','main','下载前解析为不可变 commit')}${field('保存目录','~/Models/TensorFold')}${note(source.includes('ModelScope')?'此仓库的 ModelScope 映射未核验。原型只展示任务，不声明已找到相同权重。':'镜像属于第三方；下载前核对 revision、格式、分片和哈希。',true)}`, '加入模拟队列',()=>{state.jobs.push({id:'job'+(state.jobs.length+1),model:name,source,progress:0,paused:false,canceled:false});state.downloadsTab='tasks';go('downloads');toast('已加入模拟任务，没有下载模型文件')})}
function exported(name,content,type='text/plain'){const b=new Blob([content],{type});const link=document.createElement('a');link.href=URL.createObjectURL(b);link.download=name;link.click();URL.revokeObjectURL(link.href);toast('已导出仅含演示数据的文件')}
const actions={
 'goto':go,'dismiss':dismiss,'confirm':()=>{const fn=modalCallback;if(fn){$('#modal').hidden=true;modalCallback=null;fn()}},
 'tab':v=>{const [k,val]=v.split(':');state[k]=val;render()},'reset':()=>{if(chatTimer)clearTimeout(chatTimer);location.reload()},
 'service':serviceAction,'scope':v=>{state.scope=v;render()},'save':saveSettings,'refresh':v=>toast('演示：'+v+'已刷新，无真实服务请求'),
 'model-select':id=>{state.configModel=id;go('model-config')},
 'model-load':id=>{if(id===state.model&&state.running){serviceAction('stop');return}const m=models.find(m=>m.id===id);dialog('加载 / 切换模型',`${kv('当前模型',current().name)}${kv('目标模型',m.name)}${note('TensorFold 当前没有已核验的热切换 API。按“排空请求 → 停止旧进程 → 以新模型启动 → health 与 models 就绪”处理。',true)}${select('加载失败时',['保留错误信息，提供恢复原模型入口（建议）','尝试恢复原模型（需资源可用）'])}`, '确认切换（模拟）',()=>{state.model=id;state.running=true;state.pending=false;go('overview');toast('演示：模型加载完成，API 已就绪')})},
 'favorite':id=>{state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);render()},
 'model-more':id=>dialog('模型维护',`${kv('模型',models.find(m=>m.id===id).name)}${form([select('操作',['设为默认','显示 / 隐藏','编辑显示名称','从库中移除（需确认文件范围）'])])}${note('删除操作必须区分“移除记录”和“删除磁盘模型文件”，不随扫描结果自动删除。')}`,'应用演示',()=>toast('演示：模型管理选项已更新')),
 'scan':()=>dialog('重新扫描模型目录',`${table(['模型','结果'],models.slice(0,3).map(m=>[m.name,tag('示例：文件齐全，兼容性待真实核验','blue')]))}${note('扫描不会加载模型或改写权重。')}`,'完成',()=>toast('模拟扫描结果已展示')),
 'add-dir':()=>dialog('添加模型目录',field('模型目录','~/Models/TensorFold/additional','先选择目录，再扫描兼容性')+note('目录设置不移动或删除已有文件。'),'添加（模拟）',()=>toast('演示：已添加目录，待真实扫描')),
 'directory-edit':v=>dialog('编辑 '+v,field('目录路径','~/Models/TensorFold')+note('应用后先读取目录，涉及卸载 / 重启时单独提示。'),'保存（模拟）',()=>saveSettings('server')),
 'download':download,'download-custom':()=>dialog('下载自定义仓库',form([field('仓库 ID','','namespace/repository'),select('来源',['Hugging Face 官方','HF 国内镜像（第三方）','ModelScope 国内']),field('Revision','main'),field('目标目录','~/Models/TensorFold')])+note('自定义仓库须通过模型族 / 量化 / 文件检查，不能保证任意模型可用。',true),'创建模拟任务',()=>{state.jobs.push({id:'job'+(state.jobs.length+1),model:'自定义模型（示例）',source:'待核验来源',progress:0,paused:false,canceled:false});state.downloadsTab='tasks';go('downloads')}),
 'download-settings':()=>dialog('模型下载源设置',form([select('首选来源',['HF 国内镜像（第三方）','Hugging Face 官方','ModelScope 国内']),field('Hugging Face endpoint','https://huggingface.co'),field('国内镜像 endpoint','https://hf-mirror.com'),field('ModelScope endpoint','https://modelscope.cn'),field('代理地址','','可选；真实连接性需测试'),field('下载并行文件数','4')])+note('切换源前检查 repo / revision / 文件 identity。不在原型中输入真实 token。'),'保存（模拟）',()=>toast('演示下载源已保存，未连接远端')),
 'job-pause':id=>{const j=state.jobs.find(j=>j.id===id);j.paused=!j.paused;render()},'job-progress':id=>{const j=state.jobs.find(j=>j.id===id);if(j.paused){toast('请先继续任务');return}j.progress=Math.min(100,j.progress+25);render()},'job-cancel':id=>dialog('取消下载任务',note('只取消模拟任务。真实实现保留续传文件，清理临时文件另行确认。'),'取消任务',()=>{state.jobs.find(j=>j.id===id).canceled=true;render()}),'job-retry':id=>{const j=state.jobs.find(j=>j.id===id);j.canceled=false;j.paused=false;j.progress=0;render()},
 'job-detail':id=>dialog('下载任务详情',kv('任务 ID',id)+kv('版本','demo-revision')+kv('断点续传','Range / 文件状态由下载后端管理')+kv('核验','文件清单、大小与可用哈希')+note('所有大小、进度和校验结果都是演示，未读取本机模型。'),'关闭',()=>{}),
 'map-verify':()=>dialog('仓库映射预检',kv('官方仓库',escapeHtml($('#map-hf').value))+kv('国内仓库',escapeHtml($('#map-ms').value||'未填写'))+note('尚无经过验证的国内映射。实施时需实际下载元数据、校验配置 / 权重 / MTP，不用相似名字替代。',true),'保存为待核验',()=>toast('映射记录为待核验（模拟）')),
 'apply-profile':v=>dialog('应用 '+v,note('配置档先校验字段。影响运行时参数的变化需要排空请求并重新启动。'),'应用（模拟）',()=>saveSettings('model')),
 'profile-new':v=>dialog(v==='template'?'另存为全局模板':'新建配置档',form([field('名称','新配置档'),field('虚拟 API 模型别名','local-profile'),select('复制来源',['当前模型配置','空白配置'])]),'保存（模拟）',()=>toast('模拟配置档已保存，未写真实数据')),
 'profile-import':()=>dialog('导入 JSON / Recipe',`<div class="tf-field"><label for="recipe-json">配置 JSON</label><textarea id="recipe-json">{"temperature":0.7,"top_p":0.8,"max_tokens":4096}</textarea></div>`+note('不支持的参数会拒绝应用，不自动复制 oMLX 专属字段。'),'预检（模拟）',()=>toast('演示：通用参数预检通过，待应用')),
 'config-reset':()=>dialog('恢复默认配置？',note('仅对所选范围恢复默认；当前运行配置在重启或实际应用后才改变。'),'恢复（模拟）',()=>{delete state.forms[formKey()];state.pending=true;render();toast('演示：当前范围已恢复默认，待重启生效')}),
 'show-command':()=>dialog('实际启动参数（示例）',`<div class="tf-code"><pre>tensorfold serve ${current().repo} \
  --host 127.0.0.1 --port 8082 --backend mlx \
  --context 32768 --max-tokens 4096 \
  --temperature 0.7 --top-p 0.8 --top-k 20 \
  --parallel auto --prompt-cache-gib 8</pre></div>`+note('真实参数必须从进程启动记录读回。此处只是可审阅的设计样例。'),'关闭',()=>{}),
 'cache-clear':v=>dialog('清理 '+v+'？',kv('作用范围',v)+kv('在途请求','等待完成后处理')+note('原生没有已核验的清缓存管理 API，可能需重启当前模型。不会删除模型权重；磁盘快照清理需展示文件清单。',true),'清理演示',()=>toast('演示：缓存清理流程结束，未删除任何文件')),
 'cache-probe':()=>dialog('缓存命中探测',`<textarea aria-label="探测文本" placeholder="输入需要检查的前缀文本（请勿输入私密内容）"></textarea>`+note('探测结果将区分 allocator、前缀、快照与未命中。TensorFold 当前未证实有独立 probe API；oMLX 已有管理探测端点，需重新适配。'),'探测演示',()=>toast('演示：前 1024 tokens 命中前缀缓存，后 256 tokens 为冷输入')),
 'cache-manifest':()=>dialog('快照文件清单（示例）',table(['文件','归属','大小'],[['qwen27/checkpoint-demo.bin','当前模型','128 MB · 示例'],['qwen27/prefix-demo.bin','前缀缓存','64 MB · 示例']])+note('实施时读回真实清单并限制在有效缓存目录。'),'关闭',()=>{}),
 'api-test':()=>dialog('端点检查（模拟）',table(['检查','示例结果'],[['网关 /health',tag(state.running?'Ready':'Engine offline',state.running?'green':'amber')],['/v1/models',current().repo],['Bearer key 校验','管理层设计'],['SSE / tools','未进行真实模型请求']]),'关闭',()=>{}),
 'copy':v=>copyText(v),'copy-curl':()=>copyText('curl http://127.0.0.1:8080/v1/chat/completions -H "Authorization: Bearer YOUR_API_KEY" -H "Content-Type: application/json" -d \'{"model":"local-default","messages":[{"role":"user","content":"你好"}]}\''),
 'client-config':v=>dialog(v+' 接入模板',`<div class="tf-code"><pre>${v==='Claude Code'?'需要 OpenAI → Anthropic 协议桥接，当前未配置。':'base_url = "http://127.0.0.1:8080/v1"\nmodel = "local-default"\napi_key = "YOUR_API_KEY"'}</pre></div>`+note('仅展示配置模板，不修改本机客户端。真正接入需完成真实请求、SSE 与工具调用读回验收。'),'关闭',()=>{}),
 'key-new':()=>dialog('新建子密钥（模拟）',form([field('名称','新客户端','仅使用演示名称','text','new-key-name'),select('权限',['推理 API','推理 API + 模型列表']),field('过期时间','30 天')])+note('只生成显式 demo key，刷新即重置。'),'生成模拟密钥',()=>{const name=$('#new-key-name').value||'新客户端';state.keys.push({name,masked:'tf_demo_••••_new',permission:'推理 API',status:'启用',usage:'0 次'});render();dialog('模拟密钥只展示一次',`<code>tf_demo_not_a_real_secret_${state.keys.length}</code>`+note('此字符串不是真实密钥，不赋予任何权限。'),'关闭',()=>{})}),
 'key-toggle':i=>{state.keys[i].status=state.keys[i].status==='启用'?'停用':'启用';render()},'key-revoke':i=>dialog('撤销子密钥？',note('仅移除模拟密钥记录；真实撤销会使该客户端后续请求失败。'),'撤销（模拟）',()=>{state.keys.splice(Number(i),1);render()}),
 'key-rotate':()=>dialog('轮换主 API 密钥？',note('真实轮换会影响使用旧主密钥的客户端。设计包含短期过渡与最后使用记录；本原型不改动任何凭据。',true),'预览轮换',()=>toast('模拟密钥：tf_demo_rotated_not_real')),
 'token-config':v=>dialog(v+' 凭据管理',kv('当前状态','未读取真实凭据')+select('示例状态',['保持未配置','已配置（演示）'])+note('请勿输入真实 token。实施时存入 Keychain，不回显、不进入日志、仓库或导出。'),'保存演示',()=>toast(v+' 凭据状态仅为模拟')),
 'auth-policy':()=>dialog('认证策略',kv('管理认证','独立本机安全会话 / 可选登录')+kv('推理认证','API gateway 验证 Bearer key')+kv('下载与上传','各来源独立凭据')+kv('跨源保护','Host / Origin / CSRF 依接口设计验证')+note('局域网开放和凭据权限扩大必须显式配置，不能随升级自动打开。'),'关闭',()=>{}),
 'update-check':()=>{state.updateStage=1;state.updateFail=false;go('updates');toast('模拟检查发现候选 0.3.6.3，未向 GitHub 发请求')},
 'update-next':()=>{if(state.updateStage===4){dialog('激活候选版本？',note('模拟：兼容检查与冒烟验证完成。等待请求结束后切换进程；保留旧版本回退入口。'),'激活（模拟）',()=>{state.lastVersion=state.engineVersion;state.engineVersion='0.3.6.3';state.updateStage=5;render();toast('候选版本已启用（模拟）')});return}state.updateFail=false;state.updateStage=Math.min(4,state.updateStage+1);render();toast('演示阶段：'+['','检查完成','隔离环境准备完成','兼容检查完成','冒烟验证完成'][state.updateStage])},
 'update-failure':()=>{state.updateFail=true;state.updateStage=3;render();toast('模拟验证失败：当前旧引擎保留，未激活候选')},
 'update-rollback':()=>dialog('回退到上一引擎版本？',kv('目标',state.lastVersion)+note('先验证旧环境和配置可用，再排空请求切换；模型权重与统计不会自动删除。'),'回退（模拟）',()=>{const old=state.engineVersion;state.engineVersion=state.lastVersion;state.lastVersion=old;state.updateStage=0;state.updateFail=false;render();toast('演示：已回退并读回版本')}),
 'release-assets':()=>dialog('GitHub Release 交付设计',table(['发布资产','要求'],[['.dmg','拖入应用程序安装并启动'],['SHA256SUMS.txt','安装包哈希校验'],['Release notes','App / 引擎版本、兼容性、已知限制'],['签名与公证状态','按真实证书与打包结果披露']])+note('正式验收必须从 GitHub 下载 DMG，在目标 Mac 安装、启动并验证服务控制。上传资产不等于安装闭环。'),'关闭',()=>{}),
 'upstream-info':()=>dialog('上游变更来源',kv('官方仓库','https://github.com/ashhart/TensorFold')+kv('当前原型基线','主分支源码报告 0.3.6.2 · 2026-09-29')+note('最新候选 0.3.6.3 仅用于升级流程演示，并非实际 GitHub 最新发布信息。实施时检查 release、tag 和 commit 来源。'),'关闭',()=>{}),
 'request-detail':id=>dialog('请求详情 '+id,table(['项目','示例值'],[['模型',current().name],['TTFT / Prefill / Decode','0.86s / 0.64s / 72.4 tok/s'],['Input / Cached / Output','2048 / 1327 / 326'],['Draft rounds / accepted','264 / 819'],['Acceptance rate','78.6%'],['Finish reason','stop'],['正文保存','关闭，仅存元数据']]),'关闭',()=>{}),
 'clear-stats':()=>dialog('重置 '+state.scope+' 统计？',note('真实清除需明确模型与时间范围并显示影响。原型不删除历史统计。',true),'确认演示',()=>toast('已展示统计清除流程，演示样本保持可验收')),
 'startup-error':()=>dialog('服务启动失败',kv('错误（示例）','端口 8082 已占用')+kv('进程','未达到 ready')+note('管理界面保持可用，可修改端口或查看占用进程。不会未经确认终止其他服务。',true),'查看端口设置',()=>go('server')),
 'bench-start':()=>{if(!state.running){toast('请先启动模拟服务');return}dialog('开始基准测试（模拟）',note('真实基准会消耗模型与内存，并影响在途请求。原型只展示任务结果，不执行推理。'),'运行演示',()=>{state.benchmarkDone=true;render();toast('模拟测试完成，结果明确标注为示例')})},'bench-cancel':()=>{state.benchmarkDone=false;render();toast('模拟测试已取消')},
 'bench-history':()=>dialog('基准历史（示例）',table(['测试','版本','结果'],[['cold / 2K / draft','0.3.6.2','示例结果，非真实测试'],['warm / 8K / draft','0.3.6.2','示例结果，非真实测试']]),'关闭',()=>{}),
 'chat-send':()=>{const input=$('#chat-input');const text=input?.value.trim();if(!text){toast('请先输入消息');return}if(!state.running){toast('服务已停止，请先启动模拟服务');return}state.chatHistory.push({role:'user',text});state.chatBusy=true;render();chatTimer=setTimeout(()=>{state.chatHistory.push({role:'assistant',text:'这是模拟回复，不是实际模型生成。\n\n正式实现将通过 TensorFold 的流式 Chat Completions 接口返回内容，并展示 reasoning、工具调用与每轮性能指标。'});state.chatBusy=false;render()},900)},
 'chat-stop':()=>{clearTimeout(chatTimer);state.chatBusy=false;state.chatHistory.push({role:'assistant',text:'模拟生成已取消。正式实现将中断对应请求连接，并记录取消原因。'});render()},
 'chat-new':()=>{clearTimeout(chatTimer);state.chatBusy=false;state.chatHistory=[];render();toast('新对话已创建（仅本页内存）')},
 'chat-history':v=>{if(v==='tools'){state.chatHistory=[{role:'user',text:'演示工具调用结构'},{role:'assistant',text:'tool_call: lookup_quote({case_id: "DEMO"})\n工具执行器：未连接。\n这只展示 tool schema，不能证明工具已执行。'}];render()}},
 'chat-document':()=>dialog('文档转文本',note('PDF / DOCX / 文本经管理层转换后加入提示词。当前模型为文本模型；此入口不代表支持视觉图片。原型不读取或上传任何文件。'),'了解',()=>{}),
 'quantize-preflight':()=>dialog('量化预检（模拟）',kv('源文件','保持原始权重不变')+kv('输出目录','独立目录')+kv('预算','磁盘、内存与格式需真实估算')+note('oQ 输出与 TensorFold 模型族兼容性未验证时阻断运行；此处不启动量化。',true),'保存模拟任务',()=>{state.toolJobs.push({id:'tool'+(state.toolJobs.length+1),type:'量化',name:configCurrent().name,progress:0,status:'排队'});state.toolsTab='tasks';go('model-tools');toast('量化演示任务已创建，不执行真实量化')}),
 'upload-preview':()=>dialog('上传文件清单（模拟）',table(['文件组','范围'],[['权重 / config / tokenizer','模型文件（示例）'],['README / LICENSE','模型说明'],['日志 / 密钥 / 聊天 / 缓存','排除']])+note('真正上传前确认目标仓库与可见性，本原型不会发起上传。',true),'确认演示清单',()=>{state.toolJobs.push({id:'tool'+(state.toolJobs.length+1),type:'上传',name:'示例目标仓库',progress:0,status:'排队'});state.toolsTab='tasks';go('model-tools');toast('上传演示任务已创建，没有上传文件')}),
 'tool-history':()=>dialog('模型工具任务',table(['任务','状态'],[['量化','尚未执行真实任务'],['上传','未授权真实外部写入'],['文件检查','未扫描本机模型']]),'关闭',()=>{}),
 'inspect':v=>dialog(v+' · 详情',note('此处为原型设计入口。实际文件、版本与兼容性需实施后读回验证，不使用示例替代证据。'),'关闭',()=>{}),
 'layout':()=>dialog('调整工作台布局',form([select('页面宽度',['全宽（默认）','标准','更宽']),select('指标块顺序',['服务 → 指标 → 模型 / 缓存 → 请求','服务 → 模型 → 用量 → 缓存'])])+check('显示 API 接入和引擎版本块')+note('原型演示配置入口，正式实现支持保存 / 重置布局，不影响引擎运行。'),'保存演示布局',()=>toast('布局配置已展示，待正式实现')),
 'export-profile':()=>exported('tensorfold-demo-profile.json',JSON.stringify({prototype:true,temperature:.7,top_p:.8,max_tokens:4096},null,2),'application/json'),
 'export-stats':()=>exported('tensorfold-demo-stats.csv','示例数据,模型,请求,平均TTFT\ntrue,Qwen3.8-27B,864,0.92\ntrue,Nemotron,242,1.22','text/csv'),
 'export-bench':()=>exported('tensorfold-demo-benchmark.json',JSON.stringify({prototype:true,real_inference:false,example:{ttft_seconds:.86,decode_tok_s:72.4}},null,2),'application/json'),
 'export-logs':()=>exported('tensorfold-demo-log.txt',logs.map(x=>x.join(' ')).join('\n')),
 'export-diagnostic':()=>dialog('脱敏诊断包预览',table(['包含','排除'],[['App / 引擎版本 / CLI 能力','真实密钥 / token'],['端口 / 进程退出码 / 错误','请求正文 / 对话'],['健康状态 / 内存 / 任务','用户名与完整私密路径']])+note('当前没有真实诊断数据；导出只包含演示声明。'),'导出示例',()=>exported('tensorfold-demo-diagnostic.json',JSON.stringify({prototype:true,real_data:false,engine_version:'example-0.3.6.2'},null,2),'application/json')),
 'export-capabilities':()=>exported('tensorfold-capability-draft.csv','功能,归属,适配,原型位置\n'+capabilityRows.map(r=>r.join(',')).join('\n'),'text/csv'),
 'chat-export':()=>exported('tensorfold-demo-chat.txt','模拟对话，不是真实模型输出\n'+state.chatHistory.map(m=>m.role+': '+m.text).join('\n'))
};
function copyText(t){if(navigator.clipboard?.writeText){navigator.clipboard.writeText(t).then(()=>toast('已复制示例文本')).catch(()=>dialog('复制示例',`<pre>${escapeHtml(t)}</pre>`,'关闭',()=>{}))}else dialog('复制示例',`<pre>${escapeHtml(t)}</pre>`,'关闭',()=>{})}
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(el&&!el.disabled)actions[el.dataset.action]?.(el.dataset.value||'')});
document.addEventListener('change',e=>{if(e.target.id==='stats-model'){state.statsModel=e.target.value;render()}if(e.target.id==='stats-range')toast('原型：时间范围已选择；图表保持演示数据');if(e.target.id==='config-model'){state.configModel=e.target.value;render()}if(e.target.id==='log-level'){state.logLevel=e.target.value;$('#log-output').innerHTML=filteredLogs()}if(e.target.id==='log-file')toast('原型：已选择日志文件，当前展示脱敏示例');if(e.target.id==='chat-model'){const m=models.find(m=>m.name===e.target.value);dialog('切换聊天模型？',note('聊天模型需先由服务加载；切换会重启当前引擎，历史对话保持本机记录。'),'切换演示',()=>{state.model=m.id;state.running=true;render()})}});
document.addEventListener('input',e=>{if(e.target.id==='log-search'){state.logQuery=e.target.value;$('#log-output').innerHTML=filteredLogs()}if(e.target.id==='model-search'){const q=e.target.value.toLowerCase();document.querySelectorAll('[data-model-card]').forEach(el=>el.hidden=!el.textContent.toLowerCase().includes(q))}if(e.target.id==='download-search'){const q=e.target.value.toLowerCase();document.querySelectorAll('.tf-table tbody tr').forEach(el=>el.hidden=!el.textContent.toLowerCase().includes(q))}});
document.addEventListener('keydown',e=>{if(e.key==='Escape')dismiss()});

// Additional oMLX workflow coverage, gated by TensorFold capability evidence.
const extraGates=[
 ['Native MTP / MTP assistant','TensorFold 特定模型原生；assistant 配对需核验'],
 ['DFlash draft bits / group / window / sink / block / verify','TensorFold 部分 drafter 参数原生；oMLX 专属内核与 L1/L2 不直接迁移'],
 ['VLM MTP / vision assistant','TensorFold 当前拒绝视觉输入，禁用'],
 ['MoE expert offload / SSD experts','TensorFold 有 --ssd-experts；模型与后端能力门禁'],
 ['Qwen ANE / GPU / CPU prefill','oMLX 专属实现；TensorFold 对应 --lane-kernels 等独立核验'],
 ['oQ A8 token threshold / sensitivity / enhanced','工具适配与模型输出格式未验证，禁用运行'],
 ['PLE on SSD / Qwen4 PLE','TensorFold 有 --ple-on-ssd；不等同 oMLX Qwen4 实现'],
 ['DeepSeek Engram / CED / GDN','当前 TensorFold 未证实支持，禁用'],
 ['Reasoning parser / Guided grammar','当前 TensorFold 未证实通用管理参数，工具适配门禁'],
 ['Chat template kwargs / Forced kwargs','请求级 enable_thinking 原生；额外字段逐项核验'],
 ['Tool result token 上限 / Trust remote code','管理层输入控制或加载策略，不能盲目传给引擎'],
 ['Diffusion 专属字段清洗','当前未支持 diffusion，不提供推理接口']
];
const originalModelConfig=pages['model-config'];pages['model-config']=()=>originalModelConfig()+(state.modelConfigTab==='advanced'?card('高级字段逐项适配',table(['oMLX 参考能力','TensorFold 处理方式'],extraGates)):state.modelConfigTab==='draft'?card('Drafter 细化设置',form([select('Drafter bits',['auto','4','6','8']),field('Checkpoint slots','64'),field('MLX cache GiB','3.2'),select('DFlash L1 / L2 参数',['oMLX 专属 · 当前 TensorFold 未适配'])])+note('只将该引擎版本支持的参数传入 CLI；窗口 / sink / block / verify mode 不假设跨实现等价。')):'');
const originalDownloads=pages.downloads;pages.downloads=()=>{
 if(state.downloadsTab!=='discover')return originalDownloads();
 return heading('模型下载器','远端发现与本地筛选分开，仓库详情先校验再进入下载。',button('下载源设置','download-settings'))+tabs([['catalog','TensorFold 支持模型'],['tasks','下载任务'],['discover','远端模型发现'],['sources','来源与国内映射']],'downloadsTab')+
 card('远端搜索 / 推荐',form([select('仓库来源',['Hugging Face 官方','HF 国内镜像（第三方）','ModelScope 国内'],'remote-source'),field('关键词','Qwen3.8','仅演示，不访问远端','text','remote-query'),select('模型格式',['MLX-only','全部格式（非兼容格式禁用）']),select('排序',['按兼容性优先','下载量','最近更新']),field('参数量范围','0–40B'),field('文件大小范围','0–64 GB')])+`<div class="tf-actions" style="margin-top:16px">${button('远端搜索演示','remote-search','','primary')}${button('推荐模型演示','remote-recommend')}</div>`+note('下面仅是固定示例结果。实际远端 API 搜索、推荐与 model-info 均需实现和联网验收。ModelScope 映射未证实，不自动替换官方 checkpoint。'))+
 card('仓库搜索结果（示例）',table(['模型 / 仓库','格式 / 状态','详情','下载'],models.slice(0,3).map(m=>[m.name+'<div class="tf-model-repo">'+m.repo+'</div>',tag('官方 checkpoint · 示例结果','blue'),button('模型信息','remote-info',m.id,'compact'),button('下载','download',m.id,'compact')])));
};
const originalTools=pages['model-tools'];pages['model-tools']=()=>{
 if(state.toolsTab==='tasks')return heading('量化与上传','任务状态、进度、取消与失败恢复，明确文件和外部写入范围。')+tabs([['quantize','模型量化'],['upload','模型上传'],['convert','文件检查与 Sidecar'],['tasks','量化 / 上传任务']],'toolsTab')+
 card('任务队列',state.toolJobs.length?state.toolJobs.map(j=>`<div class="tf-download-job"><div class="tf-row"><h3>${j.type} · ${escapeHtml(j.name)}</h3>${tag(j.status,j.status==='完成'?'green':'blue')}</div><div class="tf-bar"><i style="width:${j.progress}%"></i></div><div class="tf-row"><span class="tf-sub">${j.progress}% · 全部为模拟</span><div class="tf-actions">${j.status!=='完成'&&j.status!=='取消'?button('推进演示','tool-progress',j.id,'compact')+button('取消','tool-cancel',j.id,'compact'):button('重试','tool-retry',j.id,'compact')}${button('移除记录','tool-remove',j.id,'danger compact')}</div></div></div>`).join(''):'<div class="tf-empty">没有任务。可从量化预检或上传清单创建模拟任务。</div>')+note('取消不删除原始权重；移除任务记录与删除模型文件分开。真实失败包含原因、重试 / 续传和结果读回。');
 const base=originalTools();
 if(state.toolsTab==='quantize')return base+card('oQ / 量化高级适配参数',form([field('Sensitivity model','auto'),select('Text-only',['是','否（文本引擎仍拒绝视觉请求）']),select('Auto proxy sensitivity',['auto','关闭']),select('Enhanced',['未适配','启用（需格式验证）']),field('Imatrix cache 路径','~/Models/TensorFold/imatrix'),select('Imatrix reuse / strict',['复用并严格核验','不复用']),field('Imatrix samples','128'),field('Imatrix sequence length','2048'),field('MTP assistant model','按模型配对验证'),select('Preserve MTP',['保留并核验','模型不含 MTP'])])+note('这些参数来自 oMLX 量化工作流。只有对应工具及输出格式通过兼容性验证后才允许启动真实量化；原型只展示设计。'));
 if(state.toolsTab==='upload')return base+card('上传说明与身份预检',form([field('README source path','~/Models/TensorFold/README.md'),select('Auto README',['自动生成预览','采用已有 README']),select('Re-download notice',['包含量化 / 再下载说明','不自动增加说明']),select('Token validation',['未验证（原型）','验证后才允许外部写入'])])+button('Token 验证演示','upload-token-check')+note('token 验证只证明身份权限，上传完成仍需读回仓库文件、revision 和任务结果。'));
 return base;
};
const originalBench=pages.bench;pages.bench=()=>{
 if(state.benchTab==='ane')return heading('基准测试','引擎专属测试必须先通过能力门禁。')+tabs([['throughput','吞吐与延迟'],['context','上下文压力'],['accuracy','准确性 / 一致性'],['compare','Drafted / Serial 对照'],['ane','ANE 调优（能力门禁）']],'benchTab')+card('ANE tuning 对照',kv('oMLX 能力','Qwen / K2 backend · 与其他 benchmark 互斥')+kv('TensorFold 本机状态',tag('没有已核验的同等 ANE tuning 入口','amber'))+note('保留调优任务 / 结果 / 取消的工作流参考；当前不提供可运行按钮。可以运行 TensorFold 原生路径的吞吐与一致性对照。'));
 return originalBench()+(state.benchTab==='accuracy'?card('准确性测试队列',`${form([field('数据集 / 用例集','本地测试集（设计）'),select('评估类型',['用户用例成功率','输出一致性','工具 schema / 参数校验'])])}<div class="tf-actions" style="margin:16px 0">${button('加入队列','accuracy-add','','primary')}${button('清空模拟队列','accuracy-reset')}${button('取消队列','accuracy-cancel')}</div>${table(['测试任务','状态','累计结果','操作'],state.accuracyQueue.map((q,i)=>[q.name,q.status,'真实结果尚未采集',button('移除','accuracy-remove',i,'compact')]))}${note('真实实现通过任务状态 / SSE 展示进度；正确性、事实质量、exact 输出一致性分别验收。')}`):'');
};
const originalUpdate=pages.updates;pages.updates=()=>originalUpdate()+card('依赖版本与 commit 追踪',table(['组件','当前来源','版本 / SHA','处理'],[['TensorFold','GitHub release / tag / commit','实际值需安装后读回','上游原生更新 + 管理层隔离和回退'],['MLX','隔离 Python 包','0.32.2 · 示例','记录依赖锁定与变更'],['mlx-lm / mlx-vlm / mlx-embeddings / mlx-audio','oMLX 参考引擎组合','不读取或接管 oMLX 实例版本','仅适用依赖进入 TensorFold 发行清单']])+note('oMLX 提供依赖版本 / commit 链接和自身 release 检查，不能据此认为它已实现 TensorFold 的升级与 DMG 发行。App 与主引擎的 release 分开追踪。'));
const originalCache=pages.cache;pages.cache=()=>originalCache()+card('缓存层级与来源对照',table(['层级','oMLX 参考','TensorFold 状态'],[['MLX allocator cache','分配器缓存','health.memory.cache；不等于前缀命中'],['Prompt / checkpoint / spill','上下文复用与快照','CLI / 日志按版本支持'],['Hot RAM / SSD block cache','管理 API 可清理','需 TensorFold 独立适配，不能复用原实现'],['DFlash L1 / L2','oMLX drafter 内部缓存','不与主模型 cache 汇总混淆'],['GDN / cluster rank snapshots','oMLX 专属与分布式 telemetry','本机不作为已启用能力']])+note('缓存 probe 设计可扩展 messages、tools、chat_template_kwargs、thinking_budget 和 model_id；不能只检查字符串长度。'));
capabilityRows.push(...extraGates.map(r=>[r[0],'引擎专属',r[1],'模型配置 / 高级适配']),['远端搜索 / 推荐 / model-info / MLX 与大小筛选','管理层新增','HF 与 ModelScope 来源分别取证','模型下载器'],['准确性队列 / reset / cancel / SSE 与 ANE 调优','管理层新增','任务队列新增；ANE 运行受引擎门禁','基准测试'],['量化 / 上传任务生命周期与 token 校验','管理层新增','进度 / 取消 / 记录移除 / 失败恢复','量化与上传']);
actions['remote-search']=()=>toast('远端搜索演示：固定示例结果，未联网');actions['remote-recommend']=()=>toast('推荐演示：只推荐上游明确列出的 checkpoint');
actions['remote-info']=id=>{const m=models.find(m=>m.id===id);dialog('模型信息 '+m.name,kv('仓库',m.repo)+kv('后端 / 格式',m.quant)+kv('辅助权重',m.draft)+kv('大小',m.size+' · 示例')+kv('Revision / 文件清单','实际远端读取尚未执行')+note('模型结构、分片、MTP 和许可证通过核验后才允许进入可加载列表。'),'关闭',()=>{})};
actions['tool-progress']=id=>{const j=state.toolJobs.find(j=>j.id===id);j.progress=Math.min(100,j.progress+50);j.status=j.progress===100?'完成':'运行中';render()};
actions['tool-cancel']=id=>dialog('取消模拟工具任务',note('取消不删除源模型、不回滚已发生的远端写入；当前没有真实写入。'),'确认取消',()=>{state.toolJobs.find(j=>j.id===id).status='取消';render()});
actions['tool-retry']=id=>{const j=state.toolJobs.find(j=>j.id===id);j.progress=0;j.status='排队';render()};
actions['tool-remove']=id=>dialog('移除任务记录？',note('只移除模拟记录，不删除模型权重。'),'移除',()=>{state.toolJobs=state.toolJobs.filter(j=>j.id!==id);render()});
actions['upload-token-check']=()=>toast('Token 验证仅演示：没有读取凭据或发送远端请求');
actions['accuracy-add']=()=>{state.accuracyQueue.push({name:'用例集 '+(state.accuracyQueue.length+1)+' · '+current().name,status:'等待（模拟）'});render()};
actions['accuracy-remove']=i=>{state.accuracyQueue.splice(Number(i),1);render()};
actions['accuracy-reset']=()=>{state.accuracyQueue=[];render()};actions['accuracy-cancel']=()=>{state.accuracyQueue.forEach(q=>q.status='取消（模拟）');render()};

window.addEventListener('hashchange',()=>{const page=location.hash.slice(1);if(pages[page]&&page!==state.page){state.page=page;render();window.scrollTo({top:0})}});
const initial=location.hash.slice(1);if(pages[initial])state.page=initial;render();
